---
all:
  vars:
    ansible_host_key_checking: false
  children:
    consul_servers:
      vars:
        ansible_user: ubuntu
      hosts:
        192.168.68.10:
        192.168.68.11:
        192.168.68.12:
        192.168.68.8:
        192.168.68.9:

    consule_clients:
      vars:
        ansible_user: ubuntu
      hosts:
        192.168.68.16:
        192.168.68.17:
        192.168.68.18:
        192.168.68.19:
        192.168.68.20:

