---
all:
  vars:
    ansible_host_key_checking: false
  children:
    consul_servers:
      vars:
        ansible_user: ubuntu
      hosts:
        192.168.68.118:
        192.168.68.121:
        192.168.68.117:
        192.168.68.119:
        192.168.68.123:

    consule_clients:
      vars:
        ansible_user: ubuntu
      hosts:
        192.168.68.125:
        192.168.68.124:
        192.168.68.122:
        192.168.68.116:
        192.168.68.120:

