---
all:
  vars:
    ansible_host_key_checking: false
  children:
    consul_servers:
      vars:
        ansible_user: wale
      hosts:
        192.168.68.10:
        192.168.68.11:
        192.168.68.12:
        192.168.68.8:
        192.168.68.9:

    consul_clients:
      vars:
        ansible_user: wale
      hosts:
        192.168.68.13:
        192.168.68.14:
        192.168.68.15:
        192.168.68.16:
        192.168.68.17:

