---

- name: Service Running
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services["consul.service"]

- name: Service exists?
  ansible.builtin.debug:
    msg: "Consul service does not exist!"
  failed_when: ("consul.service" not in ansible_facts.services)
  when: ("consul.service" not in ansible_facts.services)

- name: Consul service is running?
  ansible.builtin.debug:
    msg: "Consul service isn't running!"
  failed_when: (ansible_facts.services["consul.service"].state != "running")
  when: (ansible_facts.services["consul.service"].state != "running")

- name: Get consul members 
  command:
    cmd: consul members
  register: consul_members
  run_once: true

- name: Debug members
  ansible.builtin.debug:
    var: consul_members.stdout_lines
  run_once: true

- name: IP/Host in members
  ansible.builtin.debug:
    msg: "IP not in memebers"
  failed_when: (inventory_hostname not in consul_members.stdout)
  when: (inventory_hostname not in consul_members.stdout)
  