---

- name: Add Consul Server Config
  template:
    src: server-config.hcl.j2
    dest: /etc/consul.d/server-config.hcl

- name: Start Consul
  systemd:
    name: consul.service
    state: restarted
    enabled: true
    daemon_reload: true
