---

- name: Change Nameserver
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install Packages
  ansible.builtin.package:
    name: "{{item}}"
  with_items:
    - unzip
    - jq

- name: Create Consul Group
  group:
    name: consul

- name: Create Consul User
  user:
    name: consul
    group: consul

- name: Install consul
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/consul{{ consul_version }}.zip

- name: Unzip Consul
  unarchive:
    src: /tmp/consul{{ consul_version }}.zip
    dest: /usr/local/bin
    remote_src: true
  notify: Restart Consul

- name: Wipe Consul Data
  file:
    path: "/opt/consul/data"
    state: absent
  when: wipe_data
  notify: Restart Consul

- name: Create Consul Directory
  file:
    path: "{{item}}"
    state: directory
    owner: consul
    group: consul
    mode: "0750"
  with_items: 
    - "{{ config_dir }}"
    - /opt/consul
    - /opt/consul/data

- name: Add Consul Common Config
  template:
    src: common-config.hcl.j2
    dest: /etc/consul.d/common-config.hcl
  notify: Restart Consul

- name: Add Consul.Service
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  notify: Restart Consul
